### ISSUE TITLE
Please change the color highlight with strings.

### ISSUE THREAD

**Issue by santosh** [vim-ruby/vim-ruby#135]
Here is an example:

```
print "This is the string."
```

Here, the quotes and the string value are highlighted in two separate colors, which shouldn't be like so. The string and the quotes should be of same color like vim does for other languages.

The different color of string and quotes distracts mind.

**Comment by santosh** [comment]
What's up guys? :smile_cat: @dkearns @graywh What have changed since then?

**Comment by juanibiapina** [comment]
Is it just me or strings get the same color as symbols? I basically get 3 or 4 colors in total with vim-ruby :(
