### ISSUE TITLE
Broken indentation inside of erb tags

### ISSUE THREAD

**Issue by calebhearth** [vim-ruby/vim-ruby#150]
I an running into an indentation issue where there is a dedent within erb tags for the second line after the erb:

What I'm seeing:

``` erb
<div>
  <% if condition %>
    <div>
    <p>foo</p>
  </div>
<% end %>
</div>
```

What it looks like in the same file without erb tags:

``` html
<div>
  <div>
    <p>foo</p>
  </div>
</div>
```

And what I'd expect:

``` erb
<div>
  <% if condition %>
    <div>
      <p>foo</p>
    </div>
  <% end %>
</div>
```

I'm seeing similar behavior for this simpler example:

``` erb
<div>
  <% if condition %>
    <p>foo</p>
  <p>bar</p>
<% end %>
</div>
```

If it makes any difference, I've also got vim-rails installed.

**Comment by dalibor** [comment]
Removing `vim-coffee-script` fixes the issue for me. I had both `vim-coffee-script` and `vim-javascript`.

**Comment by omin** [comment]
This is happening for me too (without vim-coffee-script).

**Comment by brauliobo** [comment]
seems ok after updating vim-ruby, thanks!
