### ISSUE TITLE
Syntax highlight bug when division arguments are on different lines

### ISSUE THREAD

**Issue by bogdan** [vim-ruby/vim-ruby#171]
``` ruby
a = calculate(90).and_some_long_expression /
  and_long_expression_here   
puts a
```

Cause 2nd and 3rd line highlighted as string(probably treat it as regexp).

**Comment by matthewd** [comment]
> And it would mean calling and_some_long_expression with a regex as an argument

Forgive the drive-by comment on an old issue, but: no, it wouldn't. Whitespace after an ambiguous `/`, *including* newline, makes it a division.

**Comment by tpope** [comment]
When you put it like that the solution is pretty obvious.
