### ISSUE TITLE
Syntax highlighting error when \ used to put if/unless on a new line

### ISSUE THREAD

**Issue by kaldrenon** [vim-ruby/vim-ruby#195]
Example:

    def foo
      return false if call_some_function(args)
    end

In the above case, the `end` will be correctly highlighted to match the def

    def foo
      return false \
        if call_some_function(args)
    end

Now, with the `if` on the line below, the `end` will be incorrectly highlighted as the match for the `if`

The code still performs correctly (the syntax is valid in Ruby) but the highlighting gets confused. This is more problematic when the block is nested further, and it is harder to visually detect the correct nesting without the help of the highlight.

May not present a problem in all color schemes, if the color is the same for `class` and `if`. Problem presented when using the wombat256mod colorscheme

**Comment by ilya-bobyr** [comment]
I think that if the `\%(\\\n\s*\)\<@!` exception is inserted after the `\@<=` that is already there the performance hit should be rather small.  Only in case when there is an "if" modifier Vim will do the check to see if it is not following a line continuation character.  With `\@<=` filtering out most cases already.

I have created a pull request with the change: #267

**Comment by AndrewRadev** [comment]
The performance issue is not the big problem here, it's that we just don't support backslashes like this. As I said, that particular example breaks indentation as well (as far as I remember). Even if we fix this issue, we just don't have much of a plan for dealing with these kind of constructs. Most ruby codebases can just use a different syntax.

Still, I won't close the PR out of fear of (unknown) bad consequences. I'll go ahead and merge it, but bear in mind that if we end up with related issues I may revert it.
