### ISSUE TITLE
Omnifunc is not set

### ISSUE THREAD

**Issue by duggum** [vim-ruby/vim-ruby#201]
I am using Vim 7.4 on Xubuntu 13.10. After installing vim-ruby using pathogen, I created a test file and entered the test code from the installation instructions. Everything worked fine until I tried Ctrl-X Ctrl-O, at which point I received the "Option 'omnifunc' is not set" error.

:help version shows +ruby

Thanks.

**Comment by gbell12** [comment]
Try :set omnifunc to see if it is actually set to anything.  Try :set filetype to see if there's been a filetype detected... it's the filetype plugins which usually set omnifunc.

**Comment by decapo01** [comment]
@dougireton running your commands I got 0 and the culprit is 

`:echo has("ruby")`

how do I compile vim with ruby support on ubuntu 14.04?

**Comment by decapo01** [comment]
In ubuntu 14.04 I removed the package vim-tiny and installed the package vim-nox.  After doing this I can hit ctrl-o and ctrl-x to enable auto completion and the error code "Omnifunc is not set" does not appear.
