### ISSUE TITLE
Ruby ftplugin error on opening

### ISSUE THREAD

**Issue by rcorre** [vim-ruby/vim-ruby#202]
After updating vim (v7.4, patch 1-135) a few days ago, the ruby ftplugin fails to load. I get the following errors:

```
"test.rb" [New File]
Error detected while processing function <SNR>38_query_path:
line   17:
E484: Can't open file /tmp/vHMMN3r/0
Error detected while processing /usr/share/vim/vim74/ftplugin/ruby.vim:
line  122:
E171: Missing :endif
Error detected while processing function <SNR>11_LoadFTPlugin:
line   17:
E170: Missing :endfor
```

This occurs on any .rb file, even if it is a new empty file.
A similar issue cropped up before in #166, but was due to tmux and fish shell (I am using bash and terminator, and have tried other terminals)
Version info:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan 10 2014 09:33:13)
Included patches: 1-135
Compiled by Arch Linux
```

It has the +ruby feature.

**Comment by ain** [comment]
Reproduced. Log on my side is basically the same:

```
Error detected while processing function <SNR>119_query_path:
line   17:
E484: Can't open file /var/folders/6f/1zt06xc97cv5kbw8lr8grtr80000gp/T/v2gadUX/5
Error detected while processing /opt/local/share/vim/vim74/ftplugin/ruby.vim:
line  122:
E171: Missing :endif
Error detected while processing function <SNR>15_LoadFTPlugin:
line   17:
E170: Missing :endfor
```

**Comment by ramon-rocha** [comment]
Just ran into the exact same issue as ain.  Adding `set shell=/bin/bash` to `.vimrc` per https://github.com/vim-ruby/vim-ruby/issues/166#issuecomment-21702110 seems to suppress the error.

**Comment by tpope** [comment]
Perhaps follow through on some of the existing unanswered questions.

**Comment by ryanttb** [comment]
I realize this is closed but I came across this issue with gVim 8 on Windows 10 using mingw64 + ruby installer.

Running this from a mingw64 console causes the error to appear:

    $ gvim new.rb &

Running it from a regular Command Prompt does not cause the error.

My path as seen by mingw64: 

    PATH=/c/Users/Ryan/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/Ryan/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/Program Files/PuTTY:/c/Program Files (x86)/Vim/vim80:/cmd:/mingw64/bin:/usr/bin:/c/Ruby22/bin

My path as seen by Command Prompt:

    Path=C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\PuTTY;C:\Program Files (x86)\Vim\vim80;C:\RubyDevKit\cmd;C:\RubyDevKit\mingw64\bin;C:\RubyDevKit\usr\bin;C:\Ruby22\bin;

I wound up hard coding a path array into ruby.vim instead of calling query_path:

````vim
    elseif executable('ruby')
      let g:ruby_default_path = ['C:/Ruby22/lib/ruby/2.2.0'] " s:query_path($HOME)
````

The original error for me was:

    "new.rb" [New File]
    Error detected while processing function <SNR>30_query_path:
    line   18:
    E484: Can't open file C:/Users/Ryan/AppData/Local/Temp/VIo2862.tmp
    Error detected while processing C:\Program Files (x86)\Vim\vim80\ftplugin\ruby.vim:
    line  124:
    E171: Missing :endif
    Error detected while processing function <SNR>10_LoadFTPlugin:
    line   17:
    E170: Missing :endfor
