### ISSUE TITLE
tags not working in ruby file

### ISSUE THREAD

**Issue by gs** [vim-ruby/vim-ruby#214]
Hi,

after pulling vim-ruby I cannot jump to definition,
error:
lib/calculate.rb (ruby)                                                                                                                     23,07
E121: Undefined variable: SNR
E15: Invalid expression: v:count1."tag money_to_stocks"<SNR>41_foldopen
Press ENTER or type command to continue

I found that the commit e7f48a4e7e0354abfff16cba8d579ffc29aa3863 broke this functionality in vim.

Br,
Grzegorz

**Comment by johnfig** [comment]
Was there a resolution to this? I keep on getting this error.

`E15: Invalid expression: v:count1."tag SearchHomePage"<SNR>100_foldopen`

I reinstalled ctags and vim-ruby to no avail. Any thoughts? Thank you in advance!

**Comment by tpope** [comment]
Works for me. Sounds like that `cnoremap <buffer> <SID>foldopen` might not have taken effect.

**Comment by johnfig** [comment]
This line is what got me in the vimrc @tpope `filetype plugin indent on "detect filetype automatically`. Thanks for your help!

**Comment by tpope** [comment]
I don't recommend removing that line; you're disabling all filetype and indent plugins to work around an issue.

**Comment by tpope** [comment]
You can check `cmap <buffer> <SNR>100_foldopen` (make sure the 100 matches the error message) to see if that map is there or not, which will help narrow down possible causes.

**Comment by wyne** [comment]
This just started happening to me in neovim.

```
E121: Undefined variable: SNR
E15: Invalid expression: v:count1."tag <Plug><cword>"<SNR>169_tagzv
```

Also tried reinstalling both ctags and vim-ruby. My vim-ruby is at `074200f`. Works properly when removing vim-ruby.

Neovim version:
```
:version
NVIM v0.2.1-260-g43f40b8e1
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused
-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170530-50613-171id98/build/confi
g -I/tmp/neovim-20170530-50613-171id98/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include
-I/usr/include -I/usr/include -I/tmp/neovim-20170530-50613-171id98/build/src/nvim/auto -I/tmp/neovim-20170530-50613-171id98/build/include
Compiled by justin@jwyne.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-43f40b8/share/nvim"
```

Not sure what else to look into.

**Comment by wyne** [comment]
I found the issue. I was setting `set paste` in my rc. Removing that line (it's deprecated in neovim anyway) fixed the issue for me.

**Comment by qubbit** [comment]
@wyne Thank you so much. I had been struggling with this problem for a year.

**Comment by ketiko** [comment]
I had `set nopaste` with the same issue.  Removing any setting of paste mode fixed it for me.
