### ISSUE TITLE
Add a way to configure eruby subtypes (for mime aliases and variants)

### ISSUE THREAD

**Issue by hlopko** [vim-ruby/vim-ruby#226]
As far as I know, there is no way to hook into eruby_subtype switch:

``` vim
  if b:eruby_subtype == 'rhtml'
    let b:eruby_subtype = 'html'
  elseif b:eruby_subtype == 'rb'
    let b:eruby_subtype = 'ruby'
  elseif b:eruby_subtype == 'yml'
    let b:eruby_subtype = 'yaml'
  elseif b:eruby_subtype == 'js'
    let b:eruby_subtype = 'javascript'
  elseif b:eruby_subtype == 'txt'
    " Conventional; not a real file type
    let b:eruby_subtype = 'text'
  elseif b:eruby_subtype == ''
    let b:eruby_subtype = g:eruby_default_subtype
  endif
```

[occurence-1](https://github.com/vim-ruby/vim-ruby/blob/5bc55bec639836ff5c35f58dc62988d6d1e74bd9/syntax/eruby.vim#L27-L40)
[occurence-2](https://github.com/vim-ruby/vim-ruby/blob/5bc55bec639836ff5c35f58dc62988d6d1e74bd9/ftplugin/eruby.vim#L32-L45)

Rails allows for mime aliases and variants, which can be used to further specialization of request format (resulting in partials such as show.html+tablet.erb or show.ajax_html.erb).

Would you consider solving this issue? Would you be open to a pull request adding a global dictionary mapping subtype extension to eruby_subtype?

``` vim
let g:eruby_subtype_ext_mappings = { 'ajax_html': 'html', 'html+tablet': 'html'}
```

**Comment by megosparta** [comment]
HI tried to set .docx.erb subtype as:
`  au BufRead *.docx.erb let b:eruby_subtype = 'html'` but this not work
if change file name to .DOCX.ERB than all work
I think this issue from this regexp
[](https://github.com/vim-ruby/vim-ruby/blob/master/syntax/eruby.vim#L25)

**Comment by tmccombs** [comment]
I've tried adding 

```vim
  autocmd BufRead,BufNewFile *.erb if match(getline(1), "bash") >= 0 | let b:eruby_subtype = 'sh' | endif
```

and it sets eruby_subtype to 'sh', but doesn't properly highlight the file. I think because it is setting it too late.

**Comment by arr-dev** [comment]
I have the same issue as @tmccombs 

```vim
autocmd BufNewFile,BufRead nginx*.conf.erb let b:eruby_subtype = 'nginx'
```
`eruby_subtype` is correct, but file is highlighted as `html.erb`

**Comment by tmccombs** [comment]
I found out I can do something like `setfiletype eruby.sh`. And that works.

**Comment by arr-dev** [comment]
Thanks. That seems to work in general, but https://github.com/chr4/nginx.vim embeds ERB itself 
so it causes some recursion.

Fixed by detecting it as nginx instead of erb.

```vim
autocmd BufNewFile,BufRead nginx*.conf.erb set filetype=nginx
```
