### ISSUE TITLE
Question: basic ruby indentation

### ISSUE THREAD

**Issue by milosgajdos83** [vim-ruby/vim-ruby#234]
Hi guys,

I have recently set up this plugin and expected it to work out of the box, however not even the basic ruby indentation is working for me. I've pretty simple vimrc file:

```
set nocompatible           " turn vi into vim
filetype off               " required by vundle
" VUNDLE SETUP
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()          " required
" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Track the engine.
Plugin 'SirVer/ultisnips'
" " Snippets are separated from the engine. Add this if you want them:
Plugin 'honza/vim-snippets'

" go-vim plugin by fatih
Plugin 'fatih/vim-go'

" vim-ruby plugin for ruby shit
Plugin 'vim-ruby/vim-ruby'

" vim-fugitive plugin for git
Plugin 'tpope/vim-fugitive'

" enabled vim-neatstatus line
Plugin 'maciakl/vim-neatstatus'

call vundle#end()            " required

syntax on        " Always turn the syntax on
filetype plugin indent on    " enable file detection
set expandtab    " Turn tab into spaces
set number       " Turn on numbering of lines
set showmatch    " Show matching brackets.
set matchtime=5  " Bracket blinking.
set noshowmode   " Shows vim mode

" set status line
set laststatus=2 " Always show status line.

" Match and search
set hlsearch    " highlight search
set ignorecase  " Do case in sensitive matching with
set smartcase   " be sensitive when there's a capital letter
set incsearch   " Search incrementally

" color scheme
set background=dark
colorscheme molokai
set t_Co=256

let mapleader = ","
let g:mapleader = ","

" remap hjkl
noremap ' l
noremap ; k
noremap l j
noremap k h
nnoremap . ;

" Fast saving
nmap <leader>w :w!<cr>
" Fast quitting
nmap <leader>q :q<cr>
" Fast save and quit
nmap <leader>ww :wq<cr>

" toggle the paste
map <leader>p :set paste!<CR>
" toggles search highlighting
nmap <silent> <leader>n :set hlsearch!<CR>

" Turn off auto-commenting
au FileType * setlocal formatoptions-=cro

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<c-k>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<s-c-k>"
```

Nothing crazy. However whenever editing ruby file, the indentation is 8 spaces.

Even the simple if clause turns into this:

```
if foo == "bar"
    puts "foobar"
end
```

vim-ruby does a pretty awesome job detecting ruby files like Rakefile etc., but after spending several hours investigating indentation I gave up and open this issue.

My vim version:

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 22 2014 11:49:13)
MacOS X (unix) version
Included patches: 1-430
Compiled by Homebrew
```

**Comment by davidcpell** [comment]
sorry to drum up an old issue but I was dealing with this today and found it very confusing that the installation instructions have you type this code to test the installation:

      1.upto(5) do |i|
        puts "#{i}. Infinity, the star that would not die"
      end

This very clearly has 2 spaces of indentation within the block, so I was expecting `vim-ruby`'s default indentation to be 2.

**Comment by johnfrancismccann** [comment]
Just some feedback here. I would have to agree with @davidcpell on this one. I thought the exact same thing.

**Comment by tpope** [comment]
In the 2011 PR I commented "Just 3 out of 172 ftplugins [override shiftwidth], and all 3 are languages I've never heard of". Since then that list has expanded to include Ada, Python, Rust, Scala, and (in the indent plugin) Clojure, all of which are mainstream languages. Python, in particular, is a favorite language of Bram himself, so it seems he may have changed his mind on the issue. Perhaps it is time to reconsider.
