### ISSUE TITLE
Ruby incredibly slow

### ISSUE THREAD

**Issue by solars** [vim-ruby/vim-ruby#236]
Hi there,

I don't know what to do anymore, I almost cannot work with ruby files in vim because it is so slow. Text appears a second after I typed it.. this is so annoying. I deleted plugins, use pathogen, rails.vim and some others (see below), copied this github version of vim-ruby into my bundle dir, but nothing works.

I'm using the following plugins in the bundle dir, all up to date:

ack.vim      nerdcommenter  supertab      vim-dispatch  vim-l9     vim-ruby      vim-surround
fuzzyfinder  nerdtree       taglist   vim-endwise   vim-rails  vim-ruby-refactoring  vim-textobj-rubyblock
gundo.vim    simplefold     vim-cucumber  vim-fugitive  vim-rspec  vim-rubytest      vim-yankring

I have no idea what else I could try, nothing seems to help.

Can anyone give me a hint? How can I find out what is lagging so much? It has to be related to vim-ruby/ruby syntax, but all the hints I found did not solve it. Computer is an I7.

Thanks a lot,
Christoph

**Comment by caifara** [comment]
To speed up folding, this plugin helps a lot: https://github.com/Konfekt/FastFold

source: http://vi.stackexchange.com/a/3330/7314
