### ISSUE TITLE
Incorrect matching when there is a method named "end"

### ISSUE THREAD

**Issue by jimfoltz** [vim-ruby/vim-ruby#241]
This might a rare situation. The SketchUp Ruby API has several classes that have a method named `end`[1]

In the following working example, pressing `%` on `module` will jump to the `end` for the `def self.do_it` method rather than the final `end`.

```ruby
module Namespace

  def self.do_it
    model = Sketchup.active_model
    ents = model.entities
    edge = entities.add_line(ORIGIN, [1, 1, 0])
    start_vertex = edge.start
    end_vertex = edge.end 
  end

end
```

[1] http://www.sketchup.com/intl/en/developer/docs/ourdoc/constructionline

**Comment by AndrewRadev** [comment]
Sorry it took a while to get to this issue. I've just pushed a potential fix. Could you try it out and let me know if it works for you?

**Comment by jimfoltz** [comment]
Sorry for the delay - yes this appears to be working very well. Thank you.
