### ISSUE TITLE
New release tag

### ISSUE THREAD

**Issue by wikimatze** [vim-ruby/vim-ruby#245]
Please create a new one.

**Comment by dkearns** [comment]
Why? Do you need it for packaging purposes or similar?

**Comment by wikimatze** [comment]
Yeah, I'm using a plugin manager for vim called [vim-plug](https://github.com/junegunn/vim-plug) and I don't always want to grab from master to track the changes a plugin takes.

**Comment by wikimatze** [comment]
Do you need more explanation?

**Comment by wikimatze** [comment]
Should I create release notes?

**Comment by koron** [comment]
It seems there are so many changes after [the last release](https://github.com/vim-ruby/vim-ruby/releases/tag/vim7.4).
And syntax file bundled with vim 7.4 causes some kind of slowness/[perfomance issue](https://github.com/vim-jp/issues/issues/708).

Would it be better to create a some stable release ([like this](https://github.com/vim-ruby/vim-ruby/releases/tag/stable-20130114)) and update vim bundled files?

**Comment by mattn** [comment]
any update on this?

**Comment by dkearns** [comment]
See #313.
