### ISSUE TITLE
Same colour for strings and numbers?

### ISSUE THREAD

**Issue by marnunez** [vim-ruby/vim-ruby#247]
In `a = 3` and `a = "bla"` or `a = 'bla'` both the numbers and the text inside the quotation marks appear in red. This is unlike the colouring synthax of pry, where strings are green and numbers are blue. Is this normal behaviour? If not, can it be set somehow?

**Comment by tpope** [comment]
It's a function of the color scheme. Most schemes highlight `Number` and `String` the same color.
