### ISSUE TITLE
errors while opening .rb files with vim

### ISSUE THREAD

**Issue by varunpatro** [vim-ruby/vim-ruby#253]
line   17:
E484: Can't open file /tmp/vFP9cmD/0
Error detected while processing /usr/share/vim/vim74/ftplugin/ruby.vim:
line  122:
E171: Missing :endif
Error detected while processing function <SNR>11_LoadFTPlugin:
line   17:
E170: Missing :endfor

**Comment by tpope** [comment]
Fish shell?

**Comment by varunpatro** [comment]
Yep that's right.

**Comment by varunpatro** [comment]
same errors even with bash shell

**Comment by kriox26** [comment]
@varunpatro it happened to me too, try with zsh, that fix the problem for me!

**Comment by tpope** [comment]
Supposedly Vim 7.4.276 adds support for fish shell, if you want to try a version newer than that.

**Comment by varunpatro** [comment]
Let me try with a newer vim and zsh

**Comment by Theminijohn** [comment]
Updating to `7.4` fixed this problem for me.

Build Vim directly from source, also using Homebrew:

```
# mercurial required - install if you don't already have it.
$ brew install mercurial

# install Vim
$ brew install vim

# if /usr/bin is before /usr/local/bin in your $PATH,
# hide the system Vim so the new version is found first
$ sudo mv /usr/bin/vim /usr/bin/vim72

# should return /usr/local/bin/vim
$ which vim
```

**Comment by ah-tunecore** [comment]
upgrading to vim 8.0.206 following @Theminijohn instruction's worked for me as well.
