### ISSUE TITLE
when not indetend after case statement

### ISSUE THREAD

**Issue by burningTyger** [vim-ruby/vim-ruby#278]
This is probably intended behaviour but it looks a bit confusing to me:

```ruby
case x
when nil then "foo"
when "this" then "bar"
when "that" then "baz"
end
```

I'd expect this:

```ruby
case x
  when nil then "foo"
  when "this" then "bar"
  when "that" then "baz"
end
```

**Comment by AndrewRadev** [comment]
Yes, it's intended behaviour. I understand how the second formatting makes sense to you, but I think the first style is preferred by most rubyists and there's not much sense in changing it around. If more people were interested in the different indentation, we might consider an option for it, but I doubt it'd get many supporters.

One practical benefit you could see in the first style -- if you don't use the short `then` format, the indentation looks a bit better (I think). Compare:

``` ruby
case x
when nil
  "foo"
when "this"
  "bar"
when "that"
  "baz"
end
```

and

``` ruby
case x
  when nil
    "foo"
  when "this"
    "bar"
  when "that"
    "baz"
end
```

There's two levels of indentation, and the last `when` looks a bit weird.

In any case, I think it's just one of those things that you end up getting used to with time :).

**Comment by burningTyger** [comment]
@AndrewRadev This was the friendliest :-1:  I have gotten so far. Makes absolutely sense to me now.
