### ISSUE TITLE
gf doesn't work if file name already has .rb extension

### ISSUE THREAD

**Issue by mortonfox** [vim-ruby/vim-ruby#282]
I have a Ruby source file with the following line in it:

    require 'scratch/b.rb'

When I place the cursor over that file name and type ```gf```, I get the following error message:

    E345: Can't find file "scratch/b.rb.rb" in path

However, if I change the line in the Ruby source file to:

    require 'scratch/b'

Then the ```gf``` command works fine and jumps to ```b.rb```.

**Comment by mortonfox** [comment]
I checked ```vim-ruby/ftplugin/ruby.vim``` and it appears that ```RubyCursorFile()``` now always appends the ```.rb``` extension. Would it be possible to not append that extension if the file name already ends in ```.rb```?

**Comment by tpope** [comment]
Sure. But if we are going to fix it let's figure out the exact logic rather than bolt on a special case. If I do `require 'foo.bar'`, what gets loaded? `foo.bar.rb`? `foo.bar`? Both? If so, which is higher precedence?

**Comment by mortonfox** [comment]
Shouldn't it work the same way that ```gf``` and the ```suffixesadd``` option do?
i.e. try loading ```foo.bar``` first, but if that doesn't work then try loading ```foo.bar.rb```.

That would also resolve my issue because it would try to load ```b.rb``` and succeed, before trying ```b.rb.rb```.

I see in the commit logs though that the behavior of always appending ```.rb``` was intended to avoid the problem of vim-ruby opening a directory instead of a file when both ```foo.bar``` and ```foo.bar.rb``` exist and the former is a directory. That's another complication.

**Comment by tpope** [comment]
Exactly, I've been playing whack-a-mole for a while so I'd like to be better informed about how Ruby's `require` works before continuing.

**Comment by mortonfox** [comment]
I ran some tests on ```require```. I created two files, ```foo.bar``` and ```foo.bar.rb```, each one with a different debug statement, so I can see which one was loaded. Then I created another script, ```a.rb```, with one ```require``` statement for testing. Here are the results:

1. Both ```foo.bar``` and ```foo.bar.rb``` exist.
   ```require 'foo.bar'```
   Result: foo.bar.rb loaded

2. Both ```foo.bar``` and ```foo.bar.rb``` exist.
   ```require 'foo.bar.rb'```
   Result: foo.bar.rb loaded

3. ```foo.bar.rb``` exists but not ```foo.bar```.
   ```require 'foo.bar'```
   Result: foo.bar.rb loaded

4. ```foo.bar.rb``` exists but not ```foo.bar```.
   ```require 'foo.bar.rb'```
   Result: foo.bar.rb loaded

5. ```foo.bar``` exists but not ```foo.bar.rb```.
   ```require 'foo.bar'```
   Result: LoadError: cannot load such file -- foo.bar

6. ```foo.bar``` exists but not ```foo.bar.rb```.
   ```require 'foo.bar.rb'```
   Result: LoadError: cannot load such file -- foo.bar.rb

The 5th result was a bit of a surprise until I checked the documentation at http://ruby-doc.org/core-2.2.3/Kernel.html#method-i-require

    If the filename has the extension “.rb”, it is loaded as a source file; if
    the extension is “.so”, “.o”, or “.dll”, or the default shared library
    extension on the current platform, Ruby loads the shared library as a Ruby
    extension. Otherwise, Ruby tries adding “.rb”, “.so”, and so on to the name
    until found. If the file named cannot be found, a LoadError will be raised.

Since vim-ruby deals with source files, I think we can ignore ```.so```, ```.o```, and ```.dll``` there. But it does seem that ```Kernel.require()``` appends a ```.rb``` extension if there isn't one in the file name. So vim-ruby should do something like: substitute(cfile, '\(\.rb\)\?$', '.rb', '')

I ought to check ```require_relative```, ```load```, and ```autoload``` too, to see how those work.

**Comment by tpope** [comment]
Thanks for digging in. My working assumption for the other methods is that `load` never appends anything, and the rest behave identically to `require`.
