### ISSUE TITLE
inner method and inner class does not work properly

### ISSUE THREAD

**Issue by GCorbel** [vim-ruby/vim-ruby#289]
I have this code : 

```
class PaymentService
  def initialize(user:)
    <cursor>@user = user
  end
end
```

When I type `vim`, the cursor move down but nothing is selected. `vam` works properly. I have the same issue with `viM`.

What wrong?

Thanks!

**Comment by GCorbel** [comment]
This is a conflict with [vim-mediummode](https://github.com/kbarrette/mediummode).

**Comment by dkearns** [comment]
Thanks for investigating.
