### ISSUE TITLE
Methods containing "end_" are misaligned

### ISSUE THREAD

**Issue by mrcasals** [vim-ruby/vim-ruby#291]
Hi all!

I've been using this plugin for 5+ years now, and I'd like to thank you for your work on this. I've been finding an issue, though, with method that include `end_` in their name. This `end` makes the method contents appear misaligned from the method definition, as if the `end` popped up a level of indention. See the example:

```ruby
class Test
  def end_date
  'hi'
end
end
```

I'm using the current master version of this plugin installed via Vundle. I've been seeing this issue for quite a long time now, but I cannot recall when it started. I've given a diagonal look at all the open issues and I haven't seen anything that referred to this, so I opened the issue.

Thanks!

**Comment by fenoloftaleina** [comment]
Hi, @mrcasals! It seems to work perfectly for me. Have you tried running `:PluginUpdate`?

**Comment by mrcasals** [comment]
Yes, I have everything updated. Could it be a problem with the `vim-endwise` plugin?

**Comment by fenoloftaleina** [comment]
No, it's not a problem with `vim-endwise`. I've just checked.

**Comment by fenoloftaleina** [comment]
What other plugins do you use?

**Comment by tpope** [comment]
The problem isn't that the algorithm is incorrect, but that re-indentation
is triggered before you type the underscore, correct?

**Comment by mrcasals** [comment]
@tpope I think that's the issue, but I don't know how to reproduce it. The output I posted is generated writing the code as is.

**Comment by mrcasals** [comment]
@tpope I think that's the issue, but I don't know how to reproduce it. The output I posted is generated writing the code as is.

**Comment by tpope** [comment]
Oh I misread. I *cannot* reproduce this either.

**Comment by mrcasals** [comment]
I removed all my current plugins except `vundle` and `vim-ruby` and I keep having this issue. My vimfiles are located in this repo:

https://github.com/mrcasals/vimfiles

I tried reinstalling the plugin (just to check that I was actually updating the plugin code) and the issue keeps appearing.

**Comment by tpope** [comment]
What is `:set isk?`

**Comment by mrcasals** [comment]
Sorry for the delay. Output for the command is: `  iskeyword=@,48-57,192-255`.

**Comment by dkearns** [comment]
That looks like your problem.  There's a missing '_'.

Try :verbose set isk? to see where it's being removed.

:set isk& will reset it to the default which includes the underscore.

**Comment by mrcasals** [comment]
I explicitly write `set iskeyword-=_` so that I can treat things like `a_long_method_name` like different words. I tried removing this line and the plugin works as expected. I guess this gets the regexp confused, right? Is there any other way to fix this without having to midify my `iskeyword` setup? :cry:

**Comment by dkearns** [comment]
Yes.

You can try something like this: https://github.com/bkad/CamelCaseMotion  There's several others.

**Comment by tpope** [comment]
Yeah for better or worse changing `'iskeyword'` isn't something you can do without breaking a lot more than vim-ruby.
