### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by Vm900** [vim-ruby/vim-ruby#293]
Relatively new to your plugin.How do i invoke the compiler?
Thanks you in advance

**Comment by AndrewRadev** [comment]
You can invoke the command `:compiler ruby` to set the current compiler to the one, provided by the plugin. You can place this command in your Vim configuration files, in the `ftplugin/ruby.vim` file.

To invoke the "compiler", use the `:make` command.

For more information, use `:help quickfix.txt` to learn more about the quickfix window, `compiler`, and `make`.

**Comment by Vm900** [comment]
Thanks a million @AndrewRadev
