### ISSUE TITLE
query_path function slows down sourcing `ruby.vim` 

### ISSUE THREAD

**Issue by azbshiri** [vim-ruby/vim-ruby#300]
~~`query_path` function slows down sourcing `ruby.vim` in startup because of splitting and evaluating every path in ruby default load path, if I'm not wrong. I started with commenting out lines of code from 102 to 136 and I reached to line 86 in query_path function.~~
The problem is that ruby by default searches through rubygems and that's not necessary so it causes slow operation.

```
function! s:query_path(root)
  let code = "print $:.join %q{,}"
  if &shell =~# 'sh' && $PATH !~# '\s'
    let prefix = 'env PATH='.$PATH.' '
  else
    let prefix = ''
  endif
  if &shellxquote == "'"
    let path_check = prefix.'ruby -e "' . code . '"'
  else
    let path_check = prefix."ruby -e '" . code . "'"
  endif

  let cd = haslocaldir() ? 'lcd' : 'cd'
  let cwd = getcwd()
  try
    exe cd fnameescape(a:root)
   " here's the problem =>
    let path = split(system(path_check), ',')
    exe cd fnameescape(cwd)
    return path
  finally
    exe cd fnameescape(cwd)
  endtry
endfunction
```

**Comment by jamessan** [comment]
This looks like the same issue already discussed in #248.

**Comment by azbshiri** [comment]
So what's the next step?
