### ISSUE TITLE
Namespaced class not highlighted in erb files

### ISSUE THREAD

**Issue by itspriddle** [vim-ruby/vim-ruby#305]
Since 2e67c63 a namespaced class it not highlighted properly in erb files.

Before:

<img width="143" alt="screenshot 2016-07-02 14 55 09" src="https://cloud.githubusercontent.com/assets/49571/16542018/2142f6a4-4065-11e6-9ab3-30e29db249cf.png">

After:

<img width="145" alt="screenshot 2016-07-02 14 55 55" src="https://cloud.githubusercontent.com/assets/49571/16542021/272baba6-4065-11e6-8db4-0ddc609719d4.png">

I'm afraid I'm not very good with Vim syntax rules to attempt a fix, but I can confirm that reverting 2e67c63 fixes the issue.

**Comment by tpope** [comment]
Do you have `iskeyword+=:`? That's not supported.

**Comment by itspriddle** [comment]
Nope, but while searching I found that I had `set regexpengine=1` and that was causing it. If that's also unsupported, feel free to close this.

**Comment by tpope** [comment]
Yeah AFAIK that option is mainly for debugging.
