### ISSUE TITLE
Incorrect indentation for multi-line method call with argument being passed a block

### ISSUE THREAD

**Issue by owst** [vim-ruby/vim-ruby#312]
Using `7764bf0`, the following file:

```
foo(
  x: 1,
  y: [1, 2, 3].map { |i|
    i + 1
  }
)
```

is incorrectly indented as:

```
foo(
  x: 1,
  y: [1, 2, 3].map { |i|
  i + 1
}
)
```
i.e. the body and closing brace of the block passed to `map` are not indented one step more then `y:` as I would expect.

If the `y: ...` argument is the first in the argument list, the indentation is correct:
```
foo(
  y: [1, 2, 3].map { |i|
    i + 1
  },
  x: 1
)
```

**Comment by AndrewRadev** [comment]
This seems to be introduced by a previous bugfix, in a commit message where I've had the foresight to note: "only time will tell what else will break" :). Glad to see that this breakage results in a report, I wouldn't have caught this issue myself.

I think I've managed to fix it and not re-introduce the previous issue. Could you pull master and let me know if it works for you now?

**Comment by owst** [comment]
Yes, this is now working with `87b25c5` - thanks again!
