### ISSUE TITLE
Vim 8 release

### ISSUE THREAD

**Issue by dkearns** [vim-ruby/vim-ruby#313]
Are there any objections to sending Bram a copy?

**Comment by tpope** [comment]
Please do! I'm working through my own backlog.

**Comment by AndrewRadev** [comment]
No objections on my side.

**Comment by dkearns** [comment]
Done. Tagged [stable-20160829](https://github.com/vim-ruby/vim-ruby/releases/tag/stable-20160829) for now.

**Comment by dkearns** [comment]
Tagged vim8.0

**Comment by wikimatze** [comment]
Awesome, thank you!
