### ISSUE TITLE
Heredoc indentation when interpolation

### ISSUE THREAD

**Issue by dsferreira** [vim-ruby/vim-ruby#318]
Using: `stable-20160928` tag

I'm facing some problems with indentation of heredocs when using interpolation:

```
def foo 
  <<-EOS
  #{bar}
  EOS
end 
```

**Comment by AndrewRadev** [comment]
I think I've managed to fix this. Could you check and see if it works for you now?

**Comment by AndrewRadev** [comment]
It seems like indentation in this case should be working as intended, so I'll go ahead and close the issue. Please reopen if the problem persists.
