### ISSUE TITLE
Option to disable horizontal alignment

### ISSUE THREAD

**Issue by markuspeloquin** [vim-ruby/vim-ruby#326]
I usually try to follow style guidelines for the languages I'm using, but some things I cannot abide. I discovered when upgrading to Vim 8.0 that horizontal alignment (inserting a variable number of spaces to align code with a non-leading token in the previous line) started occurring in Ruby files, particularly with a line break in the middle of an argument list. What I would like is a way to disable any/all horizontal alignment.

I'm not sure what the best way to go about this is (e.g. adding a parameter to vim-ruby). What I prefer is:
```ruby
def some_fn()
  something_long(arg0, arg1,
      even_longer_argument)
end
```

But according to Ruby style, this is wrong. It should be:
```ruby
def some_fn()
  something_long(arg0, arg1,
                 even_longer_argument)
end
# P.S. it's just a little insane that github uses variable-width font in the editor
```

Style guides aren't consistent on this. BSD KNF says *Long parameter lists are wrapped with a normal four space indent* (no alignment). Google's Java style says *this practice is permitted, but is never required* https://google.github.io/styleguide/javaguide.html#s4.6.3-horizontal-alignment (maybe align). Many say to do it, but the argument given in javaguide.html is enough for me.

**Comment by AndrewRadev** [comment]
You could write your code like this:

``` ruby
def some_fn()
  something_long(
    arg0, arg1,
    even_longer_argument
  )
end
```

**Comment by AndrewRadev** [comment]
There's an issue about this already, but, as I said there: I'll see what I can do about adding an option, but I can make no promises: https://github.com/vim-ruby/vim-ruby/issues/295

**Comment by markuspeloquin** [comment]
Whoops. I didn't find that one but I did try. Thanks for the response, Andrew!

**Comment by AndrewRadev** [comment]
It's a difficult issue to search for, I don't know if this style of indentation has an "official" name. And, unfortunately, there's quite a few issues to look through.
