### ISSUE TITLE
Can't find reason why ]M "Go to end of next method definition" doesn't work

### ISSUE THREAD

**Issue by woto** [vim-ruby/vim-ruby#331]
Hi, i'm not advanced user of VIM, may be it's not a bug, but i can't find reason why ]M and [M works incorrectly.

When i press this shortcut cursor moves to curly braces.
But when i'm executing this command `:normal ]M` vim-ruby move cursor correctly as documented.
By the way ]m for example works fine.

Why does this can happen?

I can record small video if you don't understand my question. Thanks.
ps Sorry for my English ;)

**Comment by AndrewRadev** [comment]
One explanation is that a different plugin is somehow overwriting those particular mappings. Try executing the command `:map [M` and let us know what it shows. In general, it's a good thing to try as a first step when debugging mappings.

A different possibility is that you or some plugin is defining `ruby_no_expensive`, which disables some highlighting that's used by these mappings. Try running the commands `:let g:ruby_no_expensive` and `:let b:ruby_no_expensive` to check if these variables exist. If they do, you should look for where in your configuration one of them is set and remove that.

It's definitely strange that `:normal ]M` works, though. I'm not sure how it's possible that it works, but the keybindings don't. For now, try these two things and let us know what happens.

**Comment by woto** [comment]
hmmm give me more time to attempt to describe my actions in details. But in short...
i've cleaned up vim plugins and installed clean pathogen .vim, .vimrc
and... i didn't even knew that there are same functionality already in vim :o

```
]M                      Go to [count] next end of a method (for Java or
                        similar structured language).  When not before the end
                        of a method, jump to the start or end of the class.
                        When no '}' is found after the cursor, this is an
                        error. exclusive motion. {not in Vi}
```

but i didn't see them cause of vim-ruby override this command `:help ]M` And it works with ghmmm ruby.
but! only in vim! not in gvim! uhhh (i'm talkging about `]M`, `]m` still working in both)

btw
```
:let g:ruby_no_expensive
> E121: Undefined variable: g:ruby_no_expensive
:let b:ruby_no_expensive
> E121: Undefined variable: b:ruby_no_expensive
```

**Comment by woto** [comment]
And here is `:map ]M`
![image](https://cloud.githubusercontent.com/assets/146704/22855046/57007278-f08a-11e6-8f12-a1acef796cb4.png)

**Comment by AndrewRadev** [comment]
Okay, so, this seems correct for the `]M` mapping. And `ruby_no_expensive` doesn't seem like it's set, so this shouldn't be related.

You say that something works in vim, but not in gvim? I'm not sure I completely understand this, let me see if I can summarize:

- In vim, both the mapping `]M` and the command `:normal ]M` work correctly for ruby -- going to the `end`s of methods and classes
- In gvim, the mapping `]M` works in the built-in way, jumping to `}`, but `normal ]M` works correctly for ruby

Is this correct?

**Comment by woto** [comment]
Yes you are right. Moreover `]m` works both in vim and gvim

**Comment by AndrewRadev** [comment]
This is very, very strange. I see in your screenshot that you've checked `:map ]M` in terminal Vim, could you try it in gvim as well? I can't really figure out why there'd be a difference, either way, but it's better to be sure.

**Comment by woto** [comment]
It was screenshot from gvim.
I'm recorded small screencast with my problem:
[out-9.ogv.zip](https://github.com/vim-ruby/vim-ruby/files/769643/out-9.ogv.zip)

ps. thank you for you help

**Comment by tpope** [comment]
Check `:verbose set timeout? ttimeout?`.

**Comment by woto** [comment]
@tpope 

```
  timeout
nottimeout
```

i'm already thinking about running gvim on docker )

**Comment by tpope** [comment]
Sorry I meant `:verbose set timeoutlen? ttimeoutlen?`.

**Comment by woto** [comment]
both in vim and gvim
```
  timeoutlen=1000
  ttimeoutlen=-1
```

**Comment by tpope** [comment]
That looks fine, but just to rule out any weird timing issue, you can try cranking things way up:

    set ttimeout ttimeoutlen=200 timeoutlen=5000

**Comment by tpope** [comment]
The bug fix I recently pushed might be related, if you want to update and try again.

**Comment by woto** [comment]
Oh, it's finally works in Ubuntu 18.04, also as a https://github.com/easymotion/vim-easymotion/issues/376 )
