### ISSUE TITLE
! is not considered a part of keyword

### ISSUE THREAD

**Issue by alisnic** [vim-ruby/vim-ruby#341]
if I have my cursor on a method with a bang, like this:

<img width="134" alt="screen shot 2017-04-13 at 10 18 48" src="https://cloud.githubusercontent.com/assets/1770351/24994261/af5c7296-2032-11e7-8d69-72df576e5e1f.png">

and press <C-]> to go to definition, it will not work. That is because `!` is not considered a part of keyword. For that, I've added the following line to my .vimrc:

```vim
autocmd FileType ruby setlocal iskeyword+=!
```

Does this change have a place in vim-ruby? If yes, where? I am a newbie in vim plugin development so I am not really sure whether it's worth submitting a patch for this, and if it is, in which file to put it (autoload/syntax/ftdetect/ftplugin/etc)

**Comment by tpope** [comment]
It *will* work so long as you have filetype plugins enabled, as we remap `<C-]>` to include the trailing bang. Adding `!` to `iskeyword` isn't really accurate and more importantly has numerous problems in practice.

**Comment by alisnic** [comment]
Indeed, you remap <C-]>. It was not working for me because I was using `let g:no_ruby_maps = 1`.

Thanks for your time!

**Comment by tpope** [comment]
Humor me, why did you have that option set? The maps are numerous but pretty much all conservative enhancements to built-in Vim functionality, case in point `<C-]>`.

**Comment by alisnic** [comment]
I have a pretty unorthodox mapping to `[` and `]` in normal mode to BufSurf:

```vim
Plug 'ton/vim-bufsurf'
  nmap [ :BufSurfBack<cr>
  nmap ] :BufSurfForward<cr>
```

Some mappings vim-ruby start with these chars and cause delays when pressing `[` or `]`.

**Comment by tpope** [comment]
While I'd encourage you to reconsider stomping on two built-in families of Vim commands, you can solve the problem in question with `<nowait>`.
