### ISSUE TITLE
Vim 8.0 without patch 513 breaks highlight group retrieval

### ISSUE THREAD

**Issue by tpope** [vim-ruby/vim-ruby#342]
See <https://github.com/vim/vim/commit/c96272e30e2b81e5e0c8418f09d9db4e2fcd5d73>. Fix incoming.

**Comment by tpope** [comment]
This draws my attention to the fact I reeeally doubt we need three different string/comment skips, but I'm opting not to meddle at this time.

**Comment by AndrewRadev** [comment]
Yeah, might be a good idea to look over things in that department. I'd also consider some more explicit naming of the syntax vars, but, as you say, probably not something we need to poke around at this particular time.
