### ISSUE TITLE
missing :endif in ruby.vim (reborn)

### ISSUE THREAD

**Issue by shadow-panda** [vim-ruby/vim-ruby#343]
Hello,

I still have issue #166 problem, in one specific case.
Using gVIM 8.0, I still have this error when opening ruby scripts (only for editing) in gvim from windows git bash.
To be more precise :
gvim directly (from windows, ruby not in PATH) : fine
gvim via windows git bash (ruby in PATH) : broken
gvim via windows git bash (ruby not in PATH) : fine
vim in windows git bash : fine

I tried set shell, nothing changed.
I echoed many things in query_path function, and apparently the problem is the computation of prefix, PATH value, escaping and quotes. Hardcoding value of prefix lead to the following results :

`OK let prefix = ''`
`OK let prefix = 'env PATH=".;c:\programs\ruby-2.2.3-x64-mingw32\bin" '`
`KO let prefix = 'env PATH=".;c:\programs\ruby-2.2.3-x64-mingw32\bin;c:\programs\PDFtk Server\bin" '`
=> so the space causes a problem

`KO let prefix = 'env PATH=".;c:\programs\ruby-2.2.3-x64-mingw32\bin;\"c:\programs\PDFtk Server\bin\"" '`
`KO let prefix = 'env PATH=".;c:/programs/ruby-2.2.3-x64-mingw32/bin;c:/programs/PDFtk Server/bin" '`
`KO let prefix = 'env PATH=".;c:/programs/ruby-2.2.3-x64-mingw32/bin;c:/programs/PDFtk\ Server/bin" '`
`KO let prefix = 'env PATH=".;c:/programs/ruby-2.2.3-x64-mingw32/bin;c:/programs/PDFtk\\ Server/bin" '`
`KO let prefix = 'env PATH=".;c:/programs/ruby-2.2.3-x64-mingw32/bin;c:/programs/PDFtk\\\ Server/bin" '`
`KO let prefix = 'env PATH=".;c:/programs/ruby-2.2.3-x64-mingw32/bin;c:/programs/PDFtk\\\\ Server/bin" '`
`KO let prefix = 'env PATH=".;c:/programs/ruby-2.2.3-x64-mingw32/bin;c:/programs/PDFtk\\\\\ Server/bin" '`
`KO let prefix = 'env PATH=".;c:/programs/ruby-2.2.3-x64-mingw32/bin;c:/programs/PDFtk\\\\\\ Server/bin" '`

Trying to remove double quote :
`OK let prefix = 'env PATH=.;c:/programs/ruby-2.2.3-x64-mingw32/bin;c:/programs/PDFtk\ Server/bin '`
`OK let prefix = 'env PATH=.;c:\programs\ruby-2.2.3-x64-mingw32\bin;c:\programs\PDFtk\ Server\bin '`
`OK let prefix = 'env PATH=.;c:\programs\ruby-2.2.3-x64-mingw32\bin;c:\programs\PDFtk Server\bin '`

Hope this helps.

Any clue/advice ?

**Comment by tpope** [comment]
Let's start by looking at your shell config. What's the output of `:set shell? shellslash? shellquote? shellxquote? shellxescape?`?

**Comment by shadow-panda** [comment]
Lauching gVIM from windows git bash :

```
--- Options ---
  shelltemp
  shellxquote="
  shellquote=
  shellslash

  shell=C:\programs\PortableGit-2.8.3-64-bit\usr\bin\bash
  shellxescape="&|<>()@^
```

Launching gVIM from windows :
```
--- Options ---
  shellquote=
noshellslash
  shelltemp
  shellxquote=(

  shell=C:\WINDOWS\system32\cmd.exe
  shellxescape="&|<>()@^
```

N.B. output was generated using
```
redir @a
set all
redir END
"ap
```
(hence the noshellslash which would not be that clear otherwise)

**Comment by tpope** [comment]
Try `:set shellxquote=` (i.e., set it to a blank value). This should force single quotes. Though I'm not sure single quotes will actually fix the problem.

**Comment by shadow-panda** [comment]
It works !

Should I add this to vimrc ? How can I properly set `shellxquote` depending on the context
gVIM was launched from (windows vs. windows git bash) ?

**Comment by tpope** [comment]
Good question. I'm confused why Vim goes to the trouble of automatically adjusting all these options for you, but still gets one of them wrong. I guess you would want something like

```viml
if &shell =~# 'sh'
  set shellxquote=
endif
```

Since the prefix isn't needed for all setups, I'm also going to update the conditional to disable it if `'shellxquote'` is set. I think that's the right logic?

**Comment by shadow-panda** [comment]
I chose to apply your commit to my local ruby.vim, and it works like a charm.
Thanks for the great help : fast, efficient, understandable... wow !

**Comment by allolex** [comment]
This happened with the default bash shell version on OS X High Sierra. I upgraded bash via Homebrew and the error went away.
