### ISSUE TITLE
Getting sketchy heredoc support on latest

### ISSUE THREAD

**Issue by SamSaffron** [vim-ruby/vim-ruby#348]
Latest appears to be giving me sketchy heredoc support for syntax highlighting. 

Example failing file is: https://github.com/discourse/discourse/blob/master/spec/components/pretty_text_spec.rb

**Comment by tpope** [comment]
I've opened Pandora's box.

**Comment by AndrewRadev** [comment]
@tpope Vim-elixir are testing their syntax: https://github.com/elixir-lang/vim-elixir/blob/master/spec/syntax/anonymous_function_spec.rb. Might be a lot of effort to set up, but could help while you're refactoring? Just putting the option out there.

**Comment by SamSaffron** [comment]
Looking great now @tpope , will report back if I notice anything broken

**Comment by tpope** [comment]
@AndrewRadev a good idea I will probably never follow up on. Luckily refactors of this magnitude are something I attempt less than once a year.

**Comment by wspurgin** [comment]
@tpope On master (074200f), my heredoc support looks completely gone.....
![selection_001](https://user-images.githubusercontent.com/3472781/29842070-55f665e2-8ccd-11e7-9b9b-29b1dc621838.png)

**Comment by wspurgin** [comment]
Follow up to above, looks like f19516e9e1c183dbf0add52dffb68bca8e61def6 is the culprit for me. Not sure why because that regex is :fearful: Anyway happens on daily nvim and vim@8.0.0056
