### ISSUE TITLE
Heredoc highlighting doesn’t stop properly

### ISSUE THREAD

**Issue by fanaugen** [vim-ruby/vim-ruby#350]
Heredoc strings in Ruby don’t seem to be syntax-highlighted as strings correctly on *VIM 8.0.636*

- [Example Ruby file](https://gist.github.com/anonymous/ba2315a1ca4d595623a3f6bc052b239b)
- [Diff] between a VIM version in which `vim-ruby` syntax highlighting works flawlessly (red) and one in which it’s broken (green)

Screenshot of Example Ruby file with broken highlighting:
<img width="399" alt="screen shot 2017-07-19 at 19 07 34" src="https://user-images.githubusercontent.com/1446237/28380274-03db6554-6cb7-11e7-8790-5097bce8de6e.png">

[Diff]: https://gist.github.com/anonymous/ba2315a1ca4d595623a3f6bc052b239b#gistcomment-2152101

**Comment by tpope** [comment]
I'm not typing in an entire screenshot, but `<<-HTML` on a line by itself is working fine for me.

**Comment by fanaugen** [comment]
@tpope Thank you very much for having taken a look! 

I updated the description. It appears that the problem is introduced with VIM 8.0 patch level 636

The only other difference is the version of Ruby that VIM was compiled against (ruby 2.4.0 vs. 2.4.1), so I suspeculate that this issue could be due to a bug in VIM

**Comment by tpope** [comment]
I'm spying some other heredoc issues but your example works fine. Do you actaully have vim-ruby installed?

**Comment by fanaugen** [comment]
OK, upgrading to the latest version of vim-ruby fixed the issue. Thank you for your help!
And for all the [amazing gifts](https://github.com/fanaugen/dotfiles/blob/master/vimrc.plugins#L40) you have given us.
