### ISSUE TITLE
Incorrect Heredoc highlighting: chaining method call without `()`

### ISSUE THREAD

**Issue by Kache** [vim-ruby/vim-ruby#352]
![image](https://user-images.githubusercontent.com/133218/28598948-e3a867e2-715b-11e7-9f9e-7e52b6011df5.png)

Possibly related to: https://github.com/vim-ruby/vim-ruby/issues/147? (different characters though, `}` vs `)`)

source:

```ruby
<<~HERE_DOC.chomp()
  highlights correctly
HERE_DOC

<<~HERE_DOC.chomp
  highlights as ruby code (incorrectly)
  /e.g. this is should not be a regexp
HERE_DOC
```

**Comment by Kache** [comment]
haha, Github gets it wrong too:

![image](https://user-images.githubusercontent.com/133218/28598996-18f022c8-715c-11e7-929a-f321d0c56369.png)

**Comment by tpope** [comment]
Yeah same as #147. Although thanks for using a non-confusing color scheme.

**Comment by tpope** [comment]
Whoops, I was thinking of #350, which does seem more related.

I will try to look into this eventually. In the meantime, permission granted to anyone who wants to revert my recent heredoc changes.

**Comment by dkearns** [comment]
This appears to have been fixed.
