### ISSUE TITLE
How to improve highlight

### ISSUE THREAD

**Issue by juanibiapina** [vim-ruby/vim-ruby#355]
My observation is that the highlight is very plain. Most things are just white, I see no highlight for block arguments, parenthesis, brackets, etc. Symbols and strings are the same color, commas, colons etc are also plain white.

In general, looking at the average ruby file, I see only 4 colors.

Is everyone working like this or are there solutions out there that I'm not aware of?

**Comment by Random4405** [comment]
The highlighting of block arguments is present if you install only `tpope/vim-rails`, but when both plugins are installed simultaneously, it stops working. It would be great to have it in vim-ruby too.

**Comment by tpope** [comment]
I nuked block parameter highlighting in 074200ffa39b19baf9d9750d399d53d97f21ee07. I think looks just plain stupid to highlight those but not regular function parameters or stabby proc parameters. You can turn it back on by adding `hi def link rubyBlockParameter rubyIdentifier` in `after/syntax/ruby.vim`.

More generally speaking, you can make things as garish as you like with `after/syntax/ruby.vim` and maybe a custom color scheme. The hooks are there. Personally, I *would* like to see strings and symbols as different colors, but Vim only gives us so many built-ins, and we can't exactly invent new ones.

Also try `let g:ruby_operators = 1`.
