### ISSUE TITLE
defining `ruby_operators` causes Heredocs to be highlighted as code

### ISSUE THREAD

**Issue by kmoschcau** [vim-ruby/vim-ruby#358]
Hi,

I recently found out about `ruby_operators` and set it for the first time. After a while I realized, that it causes Heredocs to be formatted wrong. (No matter which variant of Heredoc is used.)

Here is an example without the variable defined:
![noname -vim_2017-09-14_110615](https://user-images.githubusercontent.com/9497302/30421338-c0c36da4-993c-11e7-833e-3687fb4e5d91.png)

Here is another example with it defined:
![noname -vim_2017-09-14_110645](https://user-images.githubusercontent.com/9497302/30421359-d1181466-993c-11e7-964a-cf643b6279bb.png)

**Comment by kmoschcau** [comment]
Had to take new screenshots, because I forgot to close the heredoc properly. The problem still persists, though.

**Comment by sinetoami** [comment]
So, i have the same "problem" by now.    Any solution has found?

**Comment by AndrewRadev** [comment]
I tried to fix the issue in #365. @sinetoami and @kmoschcau, you could switch to the branch `fix-syntax-highlighting`, and see if the change works on your setups.

**Comment by sinetoami** [comment]
@AndrewRadev, thanks to do that! You fix that brilliantly! Works to me. So, I had made my own extended solution with interpolation too - it is so curious. My own solution works fine, but I think which a native solution works much better than an extended solution. 

Sorry for my english is not so good. But I'm greatful for your throughtful.
Thanks!

**Comment by kmoschcau** [comment]
I will be able to take a look at it earliest on Monday.

**Comment by AndrewRadev** [comment]
@sinetoami @kmoschcau An update on the state of master: the problem should be gone now on master, too. Please try updating, and, if it looks good, consider closing the issue.

**Comment by kmoschcau** [comment]
Just tested it, works for me.
