### ISSUE TITLE
Is there a way to disable rubocop linting?

### ISSUE THREAD

**Issue by karunsiri** [vim-ruby/vim-ruby#360]
I love this plugin, but the rubocop linting that adds the hyphens in the gutter and shows style guide hint in status bar makes things pretty slow.

Is there a way that I can disable the auto linting? I prefer doing manual rubocop linting before committing codes.

I searched through source code and didn't find anything.

Thank you.

**Comment by AndrewRadev** [comment]
There's no integration with rubocop in this plugin. Vim-ruby is the most basic ruby support, stuff like syntax highlighting and indentation. If you have automatic linting that runs in the background, then it's a separate plugin that does this.

Are you using some distribution that comes with a set of plugins? Try disabling them one by one to find which one does this. It might be "syntastic" or "ALE", or something like that. When you find out which one it is, there might be a granular way to disable it only for ruby, but you'll have to look into that plugin's settings.
