### ISSUE TITLE
Incorrect string highlighting 

### ISSUE THREAD

**Issue by Aaron2Ti** [vim-ruby/vim-ruby#366]
the following code have incorrect string hightliging

```ruby
  def reverse_dependencies
    self.class.joins("jobs ").where("1=1", id)
  end

  def reverse_development_dependencies
    reverse_dependencies.where("d.scope = 'development'")
  end
```

<img width="544" alt="screen shot 2018-05-05 at 9 07 29 am" src="https://user-images.githubusercontent.com/13595/39658278-4ecead3e-5044-11e8-96af-15e065c41406.png">

and, if I remove the whitespace at `self.class.joins("jobs")` it becomes

<img width="514" alt="screen shot 2018-05-05 at 9 12 55 am" src="https://user-images.githubusercontent.com/13595/39658297-a1c640c4-5044-11e8-8739-0c0dbb6c123b.png">

Regards

**Comment by tpope** [comment]
Something is very wrong if `class` is highlighted. Strip down your config and see if you can still reproduce it.

**Comment by Aaron2Ti** [comment]
thanks for quick response, I disabled most plugins, now I can confirm that this behavior was introduced by https://github.com/Valloric/vim-operator-highlight

Sorry for the miss report
