### ISSUE TITLE
private_class_method indentation

### ISSUE THREAD

**Issue by akostadinov** [vim-ruby/vim-ruby#370]
When I use `private_class_method` the indentation of following `end` is wrong
```
      private_class_method def self.add_changed(num)
        something
    end
```
While it should be:
```
      private_class_method def self.add_changed(num)
        something
      end
```

**Comment by AndrewRadev** [comment]
Sorry for taking so long to close this, and thanks to @amarshall for his work. @akostadinov, this should work now, but feel free to reopen if you find some remaining issue.
