### ISSUE TITLE
Problems with completion after '::'

### ISSUE THREAD

**Issue by Isty001** [vim-ruby/vim-ruby#371]
Hello!

I'm trying to setup vim-ruby, but I have some problems with the autocompletion. The completion only works for instance and class methods,  but wont' return anything after the `::` operator. So the `Module::Class` or `Class::Constant` cases can't be used. 

I tried to debug the `autocomplete/rubycomplete.vim` file, but unfortunately it's not completely clear what's happening. I assume some monkey patch magic is used, but for some reason it's not working in the mentioned cases. All I got is that for example when it tries to complete constants, in line 672 `eval("#{receiver}.constants")` returns an empty array. So the class is loaded, but for some reason the constants are not recognized. If I run the same snippet from a simple ruby file, it works fine, and returns the class constants of course. 

Example:
```ruby
class Test
  VERSION = 10
  TEST_CONST = 'Hello'

  def hello
  end
end

Test.new.hello # Works fine
Test::VERSION # No completion

module Hello
  class Complete
    def test
    end
  end
end

Hello::Complete.new.test # Also not completed
```

`$ ruby --version 
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]

 $ vim --version            
VIM - Vi IMproved 8.1 (2018 May 17, compiled May 30 2018 11:53:01)
Included patches: 1-26
Compiled by farkasvolgyi.istvan@virgo-pc215
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl              +vertsplit
+clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           -python            +vreplace
+conceal           +linebreak         +python3           +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       -lua               +ruby              +X11
+dialog_con_gui    +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             +xim
+digraphs          +modify_fname      +smartindent       +xpm
+dnd               +mouse             +startuptime       +xsmp_interact
-ebcdic            +mouseshape        +statusline        +xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -ldl   -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.6/config -lpython3.6m  -Wl,-rpath,/home/farkasvolgyi.istvan/.rvm/rubies/ruby-2.5.0/lib -L/home/farkasvolgyi.istvan/.rvm/rubies/ruby-2.5.0/lib -lruby -lpthread -lgmp -ldl -lcrypt -lm`

Thank you!

**Comment by AndrewRadev** [comment]
Now that #372 has been merged, can this issue be closed?
