### ISSUE TITLE
Everything after ? is losing color formatting.

### ISSUE THREAD

**Issue by eef** [vim-ruby/vim-ruby#374]
VIM Version: Latest 8.1
OS: MacOS High Sierra
Terminal: MacOS Terminal Version 2.8.2 (404)

When editing a Ruby file colors stop working after "?" I have attached a screenshot with examples.

<img width="323" alt="screen shot 2018-06-26 at 3 43 49 pm" src="https://user-images.githubusercontent.com/209288/42060235-c832abae-7aeb-11e8-874a-58f48f8fe406.png">

This happens for all color schemes.

**Comment by tpope** [comment]
Can't reproduce. Try with the default colorscheme.

**Comment by eef** [comment]
I tried the default scheme and it was still the same.  I fresh installed Vim and the plugin and it seems to have fixed it.  Thanks for getting back.
