### ISSUE TITLE
No syntax highlighting for variables inside pararell lines 

### ISSUE THREAD

**Issue by sirithcam** [vim-ruby/vim-ruby#375]
When there is a variable between | | lines there is no highlighting. 
Look at the image underneath:

<img width="486" alt="screen shot 2018-07-24 at 14 05 42" src="https://user-images.githubusercontent.com/9821595/43136980-ba90b1e4-8f4a-11e8-9bed-827cf6e97ca2.png">

Vim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul  5 2018 06:52:49)
Operating system: MacOS
My .vimrc:
```
execute pathogen#infect()
set nocompatible
syntax on
filetype plugin indent on
highlight Normal ctermfg=white
set tabstop=2
set expandtab 
set shiftwidth=2
set nu
set backspace=indent,eol,start

autocmd BufEnter * let &titlestring = ' ' . expand("%:t")    
set title
```

**Comment by tpope** [comment]
I turned that off by default. That way it matches variables outside of parallel lines.

**Comment by sirithcam** [comment]
ohh, okey, can I somehow turn it on? I'm a beginner in that thing :P

**Comment by tpope** [comment]
You'll need to override the `rubyBlockArgument` highlighting. Advice for how to do that varies.

**Comment by tpope** [comment]
You could try this in `after/syntax/ruby.vim`:

    hi link rubyBlockParameter rubyIdentifier

**Comment by sirithcam** [comment]
Thanks!! I've just added that line at the end of my .vimrc and it worked! 👍
