### ISSUE TITLE
Post Vim 8.1 release

### ISSUE THREAD

**Issue by tpope** [vim-ruby/vim-ruby#384]
So we missed the surprise Vim 8.1 release, which means the officially distributed runtime files are pretty badly out of date. I'm told Bram now periodically updates the runtime files outside of the usual release schedule, so maybe it's time to submit them again. @dkearns thoughts? I haven't done this for most of my own runtime files yet so by no means do I consider this urgent.

**Comment by dkearns** [comment]
Yes, I was just thinking the same thing but my feelings are still a bit hurt that our invitation to the 8.1 party went astray.

If I haven't done it by the new year feel free to yell at me.

**Comment by dkearns** [comment]
Bram has pushed.
