### ISSUE TITLE
[Syntax] Looks `rubyOperator` is not highlight properly 

### ISSUE THREAD

**Issue by Aaron2Ti** [vim-ruby/vim-ruby#385]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/13595/50379959-560b0500-0694-11e9-9c03-15990df78631.png">

in the preceding screen capture, operators like `<=>` and `=>` are both recognized as `<rubyDoBlock>`

P.S. I'm on on neovim v0.3.1-1-g489d32f, and have disable all other plugins, only vim-ruby left

Regards

**Comment by AndrewRadev** [comment]
Looking at the code, the `=>` key is not highlighted as an "operator". I guess it wasn't considered an "operator", exactly. It's something that connects a key and value only in a very specific context, and not generally, so maybe this was the reason behind the decision.

The other one, though, `<=>` (and also `<=` and `>=`) should be highlighted. The first thing I'd check is if you have the [`ruby_operators`](https://github.com/vim-ruby/vim-ruby/blob/a85f078d06ed11faf1b243315d67b6f37326686d/doc/ft-ruby-syntax.txt#L12-L15) setting turned on.

The other thing that seems weird to me is that the characters are substituted with `⇒` and `⇔`, accordingly. How is this performed? If it uses vim's `conceal` highlighting, it might work, but it definitely wouldn't work if there's a plugin that translates the buffer's contents upon read and write. You said that you'd disabled all plugins, but this screenshot still seems like it's using a plugin to transform these... or is it a font or something?

**Comment by Aaron2Ti** [comment]
> characters are substituted with ⇒ and ⇔

That was done by font ligatures, see here( https://github.com/be5invis/Iosevka#ligations )

> ruby_operators setting turned on

Thanks! you're right, the ruby_operators wasn't turn on.

Sorry for the disturbing
