### ISSUE TITLE
Syntax matching for rubySymbol is incorrect

### ISSUE THREAD

**Issue by bugeats** [vim-ruby/vim-ruby#386]
The text `one:` is matched as a **rubySymbol** here:

```ruby
foo = { one: 1 }
```

The text `example:` is matched as **rubyLocalVariableOrMethod** here:

```ruby
attr_reader :example
```

The text `:"name"` is matched as a **rubyString** here: 

```ruby
attr_reader :"name"
```

All of the above are incorrect. `one:` should be a hash key, `:example` should be a symbol, and `:"name"` should also be a symbol.

_Using Neovim v0.3.2_

**Comment by tpope** [comment]
All of these are highlighting as `rubySymbol` for me.

If you'd like a separate highlight group for the `{ one: 1 }` example, fine, but it *is* a symbol and it's not wrong to call it one.

**Comment by bugeats** [comment]
Hmm... this may be a Neovim thing. @tpope what Vim are you running? I might need to dig into this a bit.

**Comment by tpope** [comment]
Just tried Neovim and it's fine there too. Have you or a plugin been screwing around with `'iskeyword'`?
