### ISSUE TITLE
ruby_recommended_style is not wanted

### ISSUE THREAD

**Issue by blackjackshellac** [vim-ruby/vim-ruby#393]
The default for ruby_recommended_style should be zero.  It took me 45 minutes to figure out why my tabs were being replaced by two spaces but only when editing ruby files.

**Comment by dkearns** [comment]
Well the good news is that it won't take you that long to figure out why it's also being done for some other file types in the future.

In case you didn't discover this you can use `:verbose set shiftwidth?` to find out where an option was last set.

See #234 for a history.

It appears this issue may have already been decided upstream as the file types that set these options are either opt out or missing a variable to preemptively disable the settings.

**Comment by dkearns** [comment]
I'll consider this closed by commit d0a9fed7795c5c28db8572a06f072f5f7b03291d.
