### ISSUE TITLE
Conflict with instance variables and containedin comment autocmd

### ISSUE THREAD

**Issue by b-nik** [vim-ruby/vim-ruby#401]
I'm trying to highlight all words that start with @ in comments.

However, all instance variables are highlighted as well.  As far as I can tell by reading the vim docs, my vimrc is ok:

Here's the .vimrc part:

```vim
augroup comment_tags
  autocmd!
  autocmd Syntax * syntax match MyCommentTag "@\h\+" containedin=*Comment contained
augroup end

highlight MyCommentTag gui=bold guifg=#FFD000 ctermfg=196
```

Minimal ruby file:

```ruby
# this is a comment
# This @Word should be highlighted
def method
  # @Bug this instance variable shouldn't be highlighted, but it is
  @foo = 3
end
```

```@foo``` above is highlighted as a MyCommentTag (I used the SyntaxAttr script)

Vim 8.1-1967
Tested with just vim-ruby (initially noted with vim-polyglot, I removed it and used vim-ruby to make sure, along with everything else)

**Comment by AndrewRadev** [comment]
In order to do this, you'll need to add your custom highlighting group to the `rubyNotTop` cluster:

``` vim
autocmd Syntax * syntax cluster rubyNotTop add=MyCommentTag
```

**Comment by b-nik** [comment]
Wow, this worked, thank you!

So if I understand correctly, that line basically added MyCommentTag in a way that its containedin was ignored? Is this a bug? (vim or otherwise?)

**Comment by AndrewRadev** [comment]
I'm not an expert in syntax highlighting, but I assume that the rule "Syntax group X contains Y" takes higher priority than "Syntax group Y is contained only in Z". There's really no obvious priority that would be correct in all scenarios.

This line in vim-ruby says "The region rubyMethodBlock should contain every other top-level syntax group", which does make sense. I assume that if in-comment syntax highlighting was originally implemented in ruby's syntax, the rules might have been structured in a different way, but I don't know.
