### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by amerov** [vim-ruby/vim-ruby#405]
Incorrect indent if prev line contains method call with `/[?#]/`
Sample:
```ruby
def download_image(url)
  extname = File.extname(url).split(/[?#]/).first
    target_file = Tempfile.new()
  result
end
```

**Comment by AndrewRadev** [comment]
Just pushed a commit that should fix this. (The `rubyRegexpCharClass` syntax group was not being ignored when matching the "continuation" regex.)

Could you try it out now and let me know if it seems to work for you?

**Comment by amerov** [comment]
> Could you try it out now and let me know if it seems to work for you?

It works!
Thanks!
