### ISSUE TITLE
8.2 release

### ISSUE THREAD

**Issue by dkearns** [vim-ruby/vim-ruby#406]
Bram has stuck his finger in the wind and called for runtime updates for the imminent 8.2 release.  Any objections to sending him the goods in their current state?

**Comment by AndrewRadev** [comment]
No objection on my side.

**Comment by tpope** [comment]
I'm good with it. Thanks for the heads up, I still have loose ends that missed 8.1 too.

**Comment by tpope** [comment]
@dkearns are you still doing updates by emailing Bram a zip file? I keep hoping I missed some announcement where he allows something less onerous.

**Comment by dkearns** [comment]
Sent to Bram.

@tpope Sorry for the late reply - technical issues in the sticks.  Yes I am still emailing him the files.  However, I just had a quick look and it seems he is now accepting pull requests.  E.g., https://github.com/vim/vim/pull/5286

**Comment by tpope** [comment]
Good find, thanks.

**Comment by dkearns** [comment]
And updated.
