### ISSUE TITLE
Which compiler should Minitest be using and is it working?

### ISSUE THREAD

**Issue by nomasprime** [vim-ruby/vim-ruby#417]
Raised an [issue](https://github.com/tpope/vim-dispatch/issues/291) with vim-dispatch a while back.

Trying to figure out which compiler Minitest should be using and if that compiler's working correctly.

**Comment by tpope** [comment]
Minitest should use the `rubyunit` compiler. Please report back if you can reproduce a problem without Dispatch in the mix.
