### ISSUE TITLE
How to use this pliugin?

### ISSUE THREAD

**Issue by vimalk78** [vim-ruby/vim-ruby#418]
What features this plugin provides? Any `:` commands?

**Comment by AndrewRadev** [comment]
The plugin provides basic Ruby support for Vim. There are no special `:` commands, but there are some useful mappings and some settings you might use to improve your experience. Here's the relevant help files to look into:

- [`:help vim-ruby-plugin`](https://github.com/vim-ruby/vim-ruby/blob/master/doc/ft-ruby-plugin.txt): Filetype settings and custom mappings
- [`:help vim-ruby-indent`](https://github.com/vim-ruby/vim-ruby/blob/master/doc/ft-ruby-indent.txt): Indentation settings
- [`:help vim-ruby-syntax`](https://github.com/vim-ruby/vim-ruby/blob/master/doc/ft-ruby-syntax.txt): Syntax-related tweaks
- [`:help vim-ruby-omni`](https://github.com/vim-ruby/vim-ruby/blob/master/doc/ft-ruby-omni.txt): Information and configuration of omni completion
