### ISSUE TITLE
Visual selection not working with treesitter on Neovim

### ISSUE THREAD

**Issue by dortin42** [vim-ruby/vim-ruby#442]
Already read the wiki, but I could not find any help for this.

Neovim 0.5.1
Latest version of treesitter
Latest version of vim-ruby

if you try to select the inner method doing `Vim` (I just realized this Vim, lol) and you have an if/else it doesn't work
![imagen](https://user-images.githubusercontent.com/20261354/143912842-6e05cefd-f67a-4986-95ae-c51073edfdba.png)

Also, indent is not working if I select the entire method, it should be indented like in the previous screenshot
![imagen](https://user-images.githubusercontent.com/20261354/143913043-e649fda8-eb5d-4c66-9602-8811463e9687.png)

I disabled treesitter to check and everything (except for the indent) starts working normally

Here's my init.vim https://github.com/dortin42/dotfiles/blob/master/init.vim

**Comment by tpope** [comment]
The `im` map and indenting are both coupled to the syntax highlighting. If you're using different syntax highlighting, from treesitter or anywhere else, they'll break. I don't think there's anything we can do about this. Implementing without use of the syntax highlighting is somewhere between "difficult" and "impossible".

**Comment by dortin42** [comment]
@tpope same thing applies for indentation?

**Comment by dkearns** [comment]
Yes.
