### ISSUE TITLE
Release for Ruby 3 and Vim 9

### ISSUE THREAD

**Issue by chagar** [vim-ruby/vim-ruby#446]
* vim and neovim do not have the new syntax changes needed for Ruby 3, such as endless def and case in.
* Last release was nine months ago.
* I am assuming that a release in this repository is necessary/important for getting these changes into stock vim and neovim.
* Thank you for your important work. vim and ruby are the best.

**Comment by dkearns** [comment]
I'll do that this week if there's no objections.  Vim 9 is coming soon.

**Comment by dkearns** [comment]
Sent to the Bram.  I'll close it when he commits them to the Vim repo.

https://github.com/vim-ruby/vim-ruby/releases/tag/stable-20220329

**Comment by chagar** [comment]
@dkearns Thanks!

**Comment by tpope** [comment]
https://github.com/vim/vim/commit/46eea444d992c2ae985cabb775a5d283f8e16df3
