### ISSUE TITLE
End-less methods aren't recognized when they are class methods

### ISSUE THREAD

**Issue by ntl** [vim-ruby/vim-ruby#450]
I am trying this out, and it seems to work for instance methods, but not class methods. See the screenshot, where the cursor is indented:

![Screenshot from 2022-06-29 16-22-55](https://user-images.githubusercontent.com/31915/176547282-b16cd8aa-1bef-4cda-aac5-f43c45da180d.png)

_Originally posted by @ntl in https://github.com/vim-ruby/vim-ruby/issues/432#issuecomment-1170505227_

**Comment by AndrewRadev** [comment]
@ntl Thanks for reporting, and for the suggested fix. It's also possible to defined methods on an object directly, like `def foo.method_call`, so I ended up committing a more generic pattern, which should fix both that and the `self.` issue. Could you try it out and confirm it works?

**Comment by ntl** [comment]
@AndrewRadev just tried it out, it worked for me, thanks!
