### ISSUE TITLE
Incorrect auto indentation with string interpolation

### ISSUE THREAD

**Issue by zhengpd** [vim-ruby/vim-ruby#451]
The auto indentation is incorrect like following:

```ruby
# unexpected indentation
test = "a: #{b}"
  puts test  # <-- should not indent here

# no colon
test = "a #{b}"
puts test

# no hash sign
test = "a: {b}"
puts test

# with extra char in between
test = "a:s #{b}"
puts test
```

**Comment by AndrewRadev** [comment]
I can't seem to replicate the issue locally. Could you check that you're at the latest version, `a99282403445ac1d008b51d6edd820d5dc053ecb`? It would also be useful to see your Vim version with `vim --version`

**Comment by zhengpd** [comment]
I'm using `nvim v0.7.2` with latest vim-ruby. Maybe vim and nvim handle something differently. I adjust the regex locally to fix the issue:

```diff
--- a/indent/ruby.vim
+++ b/indent/ruby.vim
@@ -136,7 +136,7 @@ let s:end_skip_expr = function('s:EndSkipExpr')
 
 " Regex that defines continuation lines, not including (, {, or [.
 let s:non_bracket_continuation_regex =
-      \ '\%([\\.,:*/%+]\|\<and\|\<or\|\%(<%\)\@<![=-]\|:\@<![^[:alnum:]:][|&?]\|||\|&&\)\s*\%(#.*\)\=$'
+      \ '\%([\\.,:*/%+]\|\<and\|\<or\|\%(<%\)\@<![=-]\|:\@<![^[:alnum:]:][|&?]\|||\|&&\)\s*$'
 
 " Regex that defines continuation lines.
 let s:continuation_regex =
```

**Comment by AndrewRadev** [comment]
Ahh, I see, this is a problem. Neovim in particular is not an issue, but I'm guessing you're also using tree-sitter for syntax highlighting?

The way that indenting (and other things) work is by skipping regex matches in areas that match the syntax groups `rubyString`, `rubyComment`, etc. The relevant code is here: https://github.com/vim-ruby/vim-ruby/blob/a99282403445ac1d008b51d6edd820d5dc053ecb/indent/ruby.vim#L58-L84

Tree-sitter on neovim doesn't mark syntax groups, at all. I'm guessing the team hasn't gotten around to implementing a compatibility layer or something. Here's another issue that hits a similar problem: https://github.com/vim-ruby/vim-ruby/issues/442#issuecomment-982004128

Your regex change does work, but only by accident -- the final `#.*` in the pattern is meant to work on comments, so removing it breaks this example (and probably others):

``` ruby
foo + # comment
  bar

# With the regex change, this ends up indenting like so:

foo + # comment
bar
```

I think there's a way to enable tree-sitter syntax highlighting along the built-in one, so it's the only solution I can recommend. There's really no practical way that we can stop relying on syntax groups, regexes can only do so much.

To be 100% sure this is the reason for the problem, you could execute this command with the cursor inside a ruby string: `:echo synIDattr(synID(line("."), col("."), 1), "name")`. With the built-in highlighting, it should print `rubyString`. If it doesn't, then that's gotta be the problem.

**Comment by zhengpd** [comment]
@AndrewRadev Thank you for the details. Yes I'm using nvim-treesitter for highlighting, and has confirmed the issue is caused by it. After enabling the vim regex highlighting, the problem is gone.

```lua
-- nvim-treesitter config
  highlight = {
    enable = true,
    additional_vim_regex_highlighting = { "ruby" }
  },
```

**Comment by AndrewRadev** [comment]
Excellent, I'm glad it's an easy fix. I'll share that snippet in case of other issues.
