### ISSUE TITLE
with cursorline enabled, eruby tends to lose highlighting (no 'syntax sync')

### ISSUE THREAD

**Issue by bugfood** [vim-ruby/vim-ruby#453]
Hello,

I have found that when I have an eruby file named e.g. `test.ini.erb` that syntax highlighting becomes erratic. I narrowed this down to an apparent lack of syntax sync; the issue is triggered by the cursorline feature.

Steps to reproduce:
1. Download the attached [test.ini.erb.txt](https://github.com/vim-ruby/vim-ruby/files/9365096/test.ini.erb.txt); save to filename `test.ini.erb` (IMPORTANT: the file name matters).

2. Run:
```
vim -u NONE -U NONE -N -i NONE test.ini.erb
```

3. Within vim:
```
:syn on
:set cursorline
```

4. Still within vim, use the "j" key repeatedly to move down.

Observed results: Once the ` qux => 'quux',` line is reached, then syntax highlighting of the hash key assignments disappears and each downward cursor movement erases more syntax hightlighting.

Expected results: Syntax highligthing should be retained.

Workaround:
Enable syntax syncing, e.g. `:syntax sync fromstart` or `:syntax sync minlines=500`.

This is caused by:
https://github.com/vim-ruby/vim-ruby/commit/1655fecf5fa50429338ffd28697efd24f907e2d5/
...which ultimately ends up causing syntax sync to never be enabled (along with some other things):
https://github.com/vim-ruby/vim-ruby/blob/a99282403445ac1d008b51d6edd820d5dc053ecb/syntax/ruby.vim#L355,L404

I don't know what the best fix would be. The use of `ruby_no_expensive` seems to have been intentional, but I don't know what practical improvement it offers; in my case, I don't think I edit large enough files for there to be a significant overhead.

Note that enabling syntax sync does work around this particular bug, but there is much more configuration that is blocked by the use of `ruby_no_expensive`, so there may be other desirable behaviors that are missing even with the workaround present.

Thanks,
Corey

**Comment by tpope** [comment]
`ruby_no_expensive` primary disables matching `end` up with the corresponding keyword. This turns the whole block into one big syntax region, which won't work with ERB.

Let's just `syn sync` regardless and see who complains.

**Comment by bugfood** [comment]
Thanks, that was fast!
