### ISSUE TITLE
Vim 9.1

### ISSUE THREAD

**Issue by dkearns** [vim-ruby/vim-ruby#456]
A release of Vim is imminent.  Is there any reason not send the files?

I don't think I'm going to get to anything before that.

**Comment by AndrewRadev** [comment]
I don't have any coding on vim-ruby planned myself, so fine by me.

**Comment by dkearns** [comment]
Done.

Sorry @tpope I think I took the upvote on my comment to have come from you.  I meant no disrespect. :)

**Comment by tpope** [comment]
I didn't get an email notification for some reason. I'm fine with the release, hope you saw the security thing that i ported over from upstream.

**Comment by dkearns** [comment]
I did see that, thanks.
