### ISSUE TITLE
Error loading rails environment

### ISSUE THREAD

**Issue by barthezslavik** [vim-ruby/vim-ruby#52]
Ubuntu 11.04, Rails 3.1.0.rc6, Vim 7.3 (2010 Aug 15, compiled Mar 24 2011 07:07:34)

**Comment by artmees** [comment]
I have the following configurations in my vimrc
```
autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete
autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
```
and I'm also using the YouCompleteMe vim plugin... when I type something like the followin
```
some_model_object_in_rails.
Rails.
Rails.logger.
```
in all the previous cases I get `error loading rails environment`

**Comment by artmees** [comment]
after a little bit investigation... I found that this line fails https://github.com/vim-ruby/vim-ruby/blob/master/autoload/rubycomplete.vim#L468
I don't know how to debug this more than that...
and if you are wondering here is my `environment.rb` file in a standard rails 4.2 app

```rb
# Load the Rails application.
require File.expand_path('../application.rb', __FILE__)

# Initialize the Rails application.
Rails.application.initialize!
```
