### ISSUE TITLE
very slow insert mode in classes

### ISSUE THREAD

**Issue by sunaku** [vim-ruby/vim-ruby#8]
1. Start up Vim 7.2.
2. Open any Ruby file that has a class definition + methods inside.
3. Put your cursor inside the class definition and enter insert mode.
4. Type some characters and observe a few-second delay before your input appears on the screen (i.e. things are unbearably slow!).
5. Change the filetype to text (`:setf text`)
6. Enter insert mode again and type some characters (they should appear on the screen instantly).
7. Change the filetype to ruby (`:setf ruby`)
8. Enter insert mode again and type some characters (they should appear on the screen instantly).

Changing the filetype to text and back to ruby again seems to unregister the culprit that's slowing down insert mode in Ruby files.  Any idea what the real problem is, and how to fix it?  Thanks.

**Comment by art-solopov** [comment]
An RSpec file, same problem, same solution, Jan. 2016. :smile:

**Comment by alx741** [comment]
Same solution here.

This plugin is a workaround for that problem, which is apparently a Vim issue, not plugin specific (fold recomputing at inappropriate moments):

https://github.com/Konfekt/FastFold
