### ISSUE TITLE
Never return results of omni completion

### ISSUE THREAD

**Issue by hitsumabushi** [vim-ruby/vim-ruby#85]
I have a problem about omni completion of ruby code.

I upload my vimrc & bugreport.txt and sample file for reproducing this problem.
Please see https://github.com/k-sakai/freeze-vim-setting.

---
## Problem:
-   Freeze rubycomplete#Complete (Never return any result).
## Reproducing:
1.   At first, enable filetype plugin. For example, "filetype plugin on" in your vimrc.
2.   In ruby file, type the for completion of specific object's method. See below example.
## Example:

test.rb  

```
example = gets.foo
example.(type <C-x> <C-o> here)
```
## What happen:
-   omni completion never retrun any result
-   and just desplay searching message.

---

I think right behavior in this case is
-   returning the completion list or
-   finishing search and display the message "Pattern not found".

**Comment by dkearns** [comment]
See #228.

Fixed by b0decc92ee569c087d5b37419d7691c5c97f870c.
